ALTER TABLE messages ADD COLUMN IF NOT EXISTS type VARCHAR(24) NOT NULL DEFAULT 'text';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_kind VARCHAR(24);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_url TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_thumb_url TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_mime VARCHAR(128);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_duration_sec INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_bytes BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_messages_type ON messages(type);
CREATE INDEX IF NOT EXISTS idx_messages_media_kind ON messages(media_kind);
